name: flutter_ddd_skeleton_monorepo_flavoured_domain
description: Flutter Ddd Skeleton Monorepo Flavoured Domain Layer.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dio: ^4.0.6
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  freezed_annotation: ^2.2.0
  json_annotation: ^4.7.0

dev_dependencies:
  build_runner: ^2.3.0
  freezed: ^2.2.0
  import_sorter: ^4.6.0
  json_serializable: ^6.5.4
  mocktail: ^0.3.0
  very_good_analysis: ^5.1.0
