name: flutter_ddd_skeleton_monorepo_data
description: Data layer package.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  dio: ^4.0.6
  flutter:
    sdk: flutter
  json_annotation: ^4.7.0
  retrofit: ^3.3.1

dev_dependencies:
  build_runner: ^2.3.2
  import_sorter: ^4.6.0
  json_serializable: ^6.5.4
  mocktail: ^0.3.0
  retrofit_generator: ^4.2.0
  very_good_analysis: ^3.1.0
